FROM python:3.12-slim

WORKDIR /app

ENV HF_ENDPOINT=https://hf-mirror.com
ENV PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple

COPY requirements.txt .
RUN pip install --no-cache-dir --progress-bar off -r requirements.txt

COPY reportagent/ reportagent/
COPY configs/ configs/

RUN mkdir -p /app/data/pdf_library /app/data/chroma_db

ENV PYTHONPATH=/app
EXPOSE 8000
